server:
  port: 1111
spring:
  application:
    #应用名称，Feign通过@FeignClient指定服务名称进行调用
    name: eureka-feign-service-a
    #配置自定义策略
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

